"""Update tabela de sensores

Revision ID: 0a2df8991936
Revises: ddfd8002d757
Create Date: 2024-07-10 19:58:07.252788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2df8991936'
down_revision: Union[str, None] = 'ddfd8002d757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('nome', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'nome')
    # ### end Alembic commands ###
