"""Update tabela de sensores

Revision ID: 4353c6c74ab3
Revises: 3985a3324bde
Create Date: 2024-07-10 19:47:42.745152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4353c6c74ab3'
down_revision: Union[str, None] = '3985a3324bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('sensor', sa.Column('city', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'city')
    op.drop_column('sensor', 'address')
    # ### end Alembic commands ###
